<?php
/**
*  Implements hook_form_alter
 */
function customLogin_form_alter(&$form, &$form_state, $form_id) {

      if($form_id != 'user_register_form'){ // not the create account form
          return;
      }
      else{ // this is the create account form
          function validation_function(&$form, $form_state){// validate is over 18
              $minAge = strtotime(date("d")."-".date("m")."-".(date("Y")-18)); // Set min age to 18 years before todays date
              $userAge = strtotime($form_state['values']['customLogin_ask_age']['day'] . "-" .  //Get the users age based on form
                      $form_state['values']['customLogin_ask_age']['month'] . "-" . 
                      $form_state['values']['customLogin_ask_age']['year']);  
             if (!($userAge < $minAge)){//compare user age to min age
                form_set_error('date', t('Must be over 18'));
              }  
          }
          $options = array( //set the options for the age radio buttons
            'male' => t('Male'),
            'female' => t('Female'), 
          );
          $form['customLogin_ask_gender'] = array(
              '#type' => 'radios',
              '#title' => 'Gender',
              '#options' => $options,
            //  'required' => 'true',
              
          );
          $form['customLogin_ask_age'] = array(
              '#title' => 'What is your birthday?',
              '#type' => 'date',
              '#description' => 'Please enter your birthday.',
             // 'required' => 'true',
          );
       //   debug($form, true);
          $form['#validate'][] = 'validation_function'; //Validate the form before submitting
      }
}
function customLogin_user_presave(&$edit, $account, $category){// Saves of_age to user profile
    $edit['data']['of_age'] = 'yes';//This adds the of_age variable to the users profile object


}

/*
 * Implement  hook_init()
 * 
 * Redirect any unregistered user to the registration page
 */
function customLogin_init(){
    $pageURL = (@$_SERVER["HTTPS"] == "on") ? "https://" : "http://";//get the page url
    if ($_SERVER["SERVER_PORT"] != "80")
    {
        $pageURL .= $_SERVER["SERVER_NAME"].":".$_SERVER["SERVER_PORT"].$_SERVER["REQUEST_URI"];
    } 
    else 
    {
        $pageURL .= $_SERVER["SERVER_NAME"].$_SERVER["REQUEST_URI"];
    }
    global $user;
    if ( $user->uid ) {
      // Logged in user
         if($user->data['of_age']){//redundant check to verify of_age is stored against the user profile
       // debug($user, true);
             if($pageURL!="http://install.wavecloud.com/JCVD"){
             drupal_goto('JCVD');
             }
         }
    }
    else {
        // Not logged in, redirect to login/account creation page
        if($pageURL!="http://install.wavecloud.com/user/register" && $pageURL!="http://install.wavecloud.com/user" && $pageURL!="http://install.wavecloud.com/user/password"){//check to see if already on the register page (need this for redirect to even work)
            drupal_goto('user/register');
        }
    }
}

